// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/PersonService.proto

package services.person;

public final class PersonServiceProto {
  private PersonServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034services/PersonService.proto\022\010services" +
      "\032\034messages/PersonRequest.proto\032\035messages" +
      "/PersonResponse.proto2N\n\rPersonService\022=" +
      "\n\006salute\022\027.messages.PersonRequest\032\030.mess" +
      "ages.PersonResponse\"\000B\'\n\017services.person" +
      "B\022PersonServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          messages.PersonRequestProto.getDescriptor(),
          messages.PersonResponseProto.getDescriptor(),
        });
    messages.PersonRequestProto.getDescriptor();
    messages.PersonResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
