// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/PersonRequest.proto

package messages;

public interface PersonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.PersonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
