// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/PersonResponse.proto

package messages;

public final class PersonResponseProto {
  private PersonResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_PersonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_PersonResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035messages/PersonResponse.proto\022\010message" +
      "s\"`\n\016PersonResponse\022\021\n\tfirstName\030\001 \001(\t\022\020" +
      "\n\010lastName\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\r\n\005phone" +
      "\030\004 \001(\t\022\013\n\003age\030\005 \001(\005B!\n\010messagesB\023PersonR" +
      "esponseProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_messages_PersonResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_PersonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_PersonResponse_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", "Phone", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
